name: Build Package

on:
  workflow_dispatch:

  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Send Hooks BigLinux Build Package
      #   shell: bash
      #   run: |
      #     if [ -z "$(grep biglinux-package-template pkgbuild/PKGBUILD)" ];then
      #       curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package/dispatches
      #       curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package-ARM/dispatches
      #     fi
      #     curl -X POST "https://nebulaapi.nimbusnetwork.dev/webhook" \
      #       -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #             "event_type": "${{ github.repository }}",
      #             "branch": "${{ github.ref_name }}",
      #             "url": "https://github.com/${{ github.repository }}"
      #           }'

      # - name: Invoke deployment hook
      #   uses: johannes-huther/webhook.sh@v1
      #   env:
      #     webhook_url: https://nebulaapi.nimbusnetwork.dev/webhook
      #     webhook_secret: ${{ secrets.WEBHOOK_TOKEN }}
      #     data: '{ "event_type": "${{ github.repository }}", "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}"}'
                  #xpto28
                  
                
                  
                  
   
 

